
project_id = "exxgffyqljmgxyoqfmgw"

[storage.avatars]
public = true

[[storage.policies]]
name = "Allow anyone to read avatars"
storage.objects = "avatars"
operations = ["select"]
for = "authenticated, anon"
expression = "true"

[[storage.policies]]
name = "Allow authenticated users to upload avatars"
storage.objects = "avatars"
operations = ["insert", "update"]
for = "authenticated"
expression = "auth.uid() = SPLIT_PART(storage.foldername(name), '/', 1)::uuid"

[[storage.policies]]
name = "Allow users to delete their own avatars"
storage.objects = "avatars"
operations = ["delete"]
for = "authenticated"
expression = "auth.uid() = SPLIT_PART(storage.foldername(name), '/', 1)::uuid"
