// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://exxgffyqljmgxyoqfmgw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4eGdmZnlxbGptZ3h5b3FmbWd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4ODE5OTksImV4cCI6MjA1ODQ1Nzk5OX0.MGI3n9RAmY-3rUcUt5NlzZXy1IJdhjpTy8JB8hLG--k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);